import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const svgGilroyMedium = localFont({
  src: "../src/assets/fonts/svn-gilroy-medium.otf",
  weight: "400",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Coffee House",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${svgGilroyMedium.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
